// Generated by LiveScript 1.3.1
var x$;
x$ = angular.module('xmtMidterm', []);
x$.config(['$compileProvider', '$httpProvider'].concat(function($compileProvider, $httpProvider){
  return $compileProvider.aHrefSanitizationWhitelist(/^\s*(blob:|http:\/\/localhost|https:\/\/loading.io\/)/);
}));
x$.controller('xmtMtMain', ['$scope'].concat(function($scope){
  var getCookie;
  $scope.ans = {
    css1: "<span>才不是為了你呢</span>",
    css2: "<h1>就少一個插座用，很不方便</h1>\n<style type=\"text/css\">\n</style>",
    css3: "<link>\n<div></div>",
    css4: "<div style=\"\"></div>",
    selector1: "???? {\n  color: red;\n}\n???? {\n  background: black;\n}",
    selector2: "<div class=\"btn\">發射核彈</div>\n<style type=\"text/css\">\n  .btn {\n    background: #249;\n    color: white;\n    padding: 5px 10px;\n  }\n  ????\n</style>",
    selector4: "a.item - 第 ? 行\n.active a.item - 第 ? 行\n#link.dropdown a.item - 第 ? 行\n.item.large - 第 ? 行",
    bootstrap2: "看到格子這麼大應該就知道有很多字要打了吧！請善用複製貼上"
  };
  getCookie = function(name){
    var value, parts;
    value = "; " + document.cookie;
    parts = value.split("; " + name + "=");
    if (parts.length === 2) {
      return parts.pop().split(";").shift();
    }
  };
  ['html', 'css', 'selector', 'bootstrap'].map(function(t){
    return [1, 2, 3, 4].map(function(v){
      var name, label, value;
      name = t + "" + v;
      label = "ans." + name;
      $scope.$watch(label, function(n, o){
        if (n) {
          document.cookie = "ans." + t + v + "=" + encodeURIComponent(n);
          return $scope.download = null;
        }
      });
      value = getCookie(label);
      if (value && value !== 'undefined') {
        return $scope.ans[name] = decodeURIComponent(value);
      }
    });
  });
  return $scope.submit = function(){
    var payload, url;
    if (!$scope.id) {
      return;
    }
    payload = {
      ans: $scope.ans,
      id: $scope.id,
      name: $scope.name
    };
    url = URL.createObjectURL(new Blob([JSON.stringify(payload)], {
      type: "application/json"
    }));
    return $scope.download = url;
  };
}));